update for uniswap adapter
innovation-upstream/hedgepie-dev pull request #148
Opened 2022-08-31 12:29 UTC by naruto0913

PR for polygon uniswap adapter

2022-09-01 14:47 UTC, daiki-iu requested changes

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/contracts/HedgepieInvestor.sol
> -
@naruto0913  Is there any specific reason that `_getLp` function was removed from Investor contract?

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/contracts/HedgepieInvestorMatic.sol
> +    }
@naruto0913  What's the purpose of this `testcase` function?

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/contracts/adapters/polygon/uniswap/uniswap-lp-adapter.sol
> +contract UniswapLPAdapter is BaseAdapterMatic {
@naruto0913  let's rename this to `UniswapV3LpAdapter`

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/hardhat.config.js
> +      allowUnlimitedContractSize: true,
@naruto0913  we don't need `allowUnlimitedContractSize` config. It will cause a problem of deployment in future.

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +        // Deploy Quick LPFarm Adapter contract
Wrong comment!

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +        const QuickAdapter = await ethers.getContractFactory("UniswapLPAdapter");
Wrong name, should be replaced to uniswapV3LpAdapter

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +        this.aAdapter = await QuickAdapter.deploy(
Wrong name, should be replaced to uniswapV3LpAdapter

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +        const USDC = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
Move to line #20

2022-09-01 14:47 UTC, daiki-iu commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +    // });
Should be removed.

2022-09-01 14:53 UTC, naruto0913 commented on v1-contract/contracts/HedgepieInvestor.sol
> -
@daiki-iu 
I found that that function was declared but never used.

2022-09-01 14:54 UTC, naruto0913 commented on v1-contract/contracts/HedgepieInvestorMatic.sol
> +    }
@daiki-iu 
That codes for the debugging using tenderly fork.
I will remove them.

2022-09-01 14:54 UTC, naruto0913 commented on v1-contract/contracts/adapters/polygon/uniswap/uniswap-lp-adapter.sol
> +contract UniswapLPAdapter is BaseAdapterMatic {
@daiki-iu 
Yes, will change it.

2022-09-01 14:54 UTC, naruto0913 commented on v1-contract/hardhat.config.js
> +      allowUnlimitedContractSize: true,
@daiki-iu 
Got you.

2022-09-01 14:54 UTC, naruto0913 commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +        // Deploy Quick LPFarm Adapter contract
Got you

2022-09-01 14:55 UTC, naruto0913 commented on v1-contract/test/integration/adapters/polygon/uniswap/uniswap-lp-adapter.test.js
> +        this.aAdapter = await QuickAdapter.deploy(
Ok

2022-09-09 16:45 UTC, daiki-iu approved these changes

2022-09-09 16:45 UTC, merged