codes push for curve adapter
innovation-upstream/hedgepie-dev pull request #166
Opened 2022-09-13 13:37 UTC by naruto0913

PR for polygon curve adapter

2022-09-15 14:24 UTC, daiki-iu requested changes
@naruto0913  LGTM!
I need some updates in this PR.
- build a separate HedgepieLibraryMatic
- build a separate AdapterManger

2022-09-15 16:32 UTC, daiki-iu requested changes

2022-09-15 16:32 UTC, daiki-iu commented on v1-contract/contracts/HedgepieAdapterManager.sol
> +
@naruto0913  we don't need these functions here.

2022-09-15 16:32 UTC, daiki-iu commented on v1-contract/contracts/HedgepieInvestor.sol
>  contract HedgepieInvestor is Ownable, ReentrancyGuard {
@naruto0913  we don't need any change in HedgepieInvestor contract

2022-09-15 16:32 UTC, daiki-iu commented on v1-contract/contracts/libraries/HedgepieLibrary.sol
@naruto0913  we don't need any change in this file.

2022-09-15 16:32 UTC, daiki-iu commented on v1-contract/contracts/interfaces/IAdapterManager.sol
> +        );
@naruto0913  can we add IAdapterManagerMatic file?

2022-09-15 17:04 UTC, naruto0913 commented on v1-contract/contracts/interfaces/IAdapterManager.sol
> +        );
Ok

2022-09-15 17:04 UTC, naruto0913 commented on v1-contract/contracts/libraries/HedgepieLibrary.sol
Ok, got you

2022-09-15 17:04 UTC, naruto0913 commented on v1-contract/contracts/HedgepieInvestor.sol
>  contract HedgepieInvestor is Ownable, ReentrancyGuard {
Ok

2022-09-26 15:27 UTC, daiki-iu approved these changes
@naruto0913  LGTM!

2022-09-26 15:27 UTC, merged