feat: 3pqe3jd - yearn finance adapter [SC]
innovation-upstream/hedgepie-dev pull request #195
Opened 2022-10-21 16:37 UTC by naruto0913

PR for ETH yearn finance adapter
1. Include only files related to yearn finance
2. Add pendingReward
3. add comments for all functions

2022-10-24 15:12 UTC, daiki-iu requested changes
@naruto0913  All lgtm!
- minor update to remove unnecessary comment
- add test cases for pendingReward function

2022-10-24 15:59 UTC, 0xmainnov approved these changes

2022-10-25 12:37 UTC, daiki-iu approved these changes
@naruto0913  LGTM!

2022-10-25 12:39 UTC, 0xmainnov approved these changes

2022-10-25 12:41 UTC, merged

2022-10-25 12:42 UTC, daiki-iu commented
@naruto0913 PR#195 is merged with 2 approvals.