feat: code optimization
innovation-upstream/hedgepie-dev pull request #212
Opened 2022-11-21 11:15 UTC by naruto0913

Main updates
1. Remove useless functions in libraryETH and adapterETH contract
2. update variable order of deposit function in each ETH adapter contracts
3. add shared folder for integration testing and using same function in each testing files

2022-11-21 13:03 UTC, daiki-iu requested changes
@naruto0913  Can we create some fixtures for Investor, AdapterManager, YBNFT contracts?

2022-11-22 13:11 UTC, daiki-iu commented
@naruto0913  there is a conflict that should be fixed to proceed review.

2022-11-22 13:34 UTC, daiki-iu approved these changes
@naruto0913  LGTM!

2022-11-22 15:20 UTC, 0xmainnov approved these changes

2022-11-22 16:24 UTC, merged